a-company-jp/gaishi-hackathon-app

.github/labeler.yml, .github/workflows/auto-label-conflicts.yaml, .github/workflows/auto-labeler.yaml
=> Labeler CIの導入

.github/workflows/deploy-cloudrun-backend.yaml, backend/build/Dockerfile.prod
Backend Deploy用のCIを追加
Cacheとかやってみました
=> Backend Deploy用CIの追加

webapp/.env.sample, webapp/.gitignore, webapp/src/app/mock/[id].tsx, webapp/src/app/mock/page.tsx
- **🔧 .env.sample**
- **🐛 mock/page → mock/[id].tsx**
=> Mockページのエラー解消

backend/.air.toml, backend/build/Dockerfile.dev, backend/cmd/dev/main.go, backend/go.mod, backend/go.sum, backend/pkg/settings/Infrastructure.go, backend/pkg/settings/setting.sample.yaml, backend/pkg/settings/setting.template.yaml, docker-compose.yml
- **🍱 move .air.toml to backend folder**
- **🔧 add redis field in pkg/settings**
- **🧑‍💻 fix backend path for local dev**
- **✨ redis load**
=> Backend local開発環境の修正 + Redis読み込みの実装

infra/envs/dev/google_cloud_run_v2.tf, infra/envs/dev/google_compute_network.tf, infra/envs/dev/google_dns.tf, infra/envs/dev/imports.tf
- **🧱 import google_compute_subnetwork.default**
- **♻️ refactor managed_zone,network**
- **🧱 add record for acme_challenge *.i.a.shion.pro**
=> ACME CHALLENGE用レコード追加 / VPCインポート

infra/envs/dev/google_dns.tf
Updating acme_challenge to authenticate through dns
=> 🧱 update record for acme_challenge *.i.a.shion.pro

backend/cmd/dev/migrate.go
初期マイグレーション時にバージョン情報が取得できなく落ちる問題が発生した
=> 初回Migration実施時のハンドリング

.github/workflows/terragrunt-apply.yml
- **👷 fix paths param**
なんか毎回mainでtf applyが実行されるからおかしいなとは思ってた
=> Applyのtrigger対象パス変更

.github/workflows/check-generate.yml
=> 👷 fix go.sum cache settings

graphql/schema.graphqls, webapp/src/app/health/page.tsx, webapp/src/gql/__generated__/gql.ts, webapp/src/gql/__generated__/graphql.ts
- **✨ health graphql query**
- **✨ health page**
=> Health queryの追加

backend/db_schema/config.json
一旦大きくmigrationを書き換えるため、migrationを0にします
=> 🗃️ migrate to 0

backend/graph/generated.go, backend/graph/schema.resolvers.go
graphqlの変更を反映(backendのコード生成更新)
=> Healthによる変更の反映

.github/workflows/lint-frontend.yml, webapp/src/app/health/page.tsx
- **📦️ update gql generated code**
- **🐛 fix way to call graphql**
=> Graphqlのフロントエンドの叩き方修正

backend/cmd/dev/migrate.go
=> 🐛 fix logic to drop all tables on version 0

.github/workflows/deploy-gcs-frontend.yaml, webapp/src/app/not-found.tsx
=> GCSデプロイworkflowの修正

webapp/next.config.ts
/start が start.htmlとして生成されてしまっていた
/start/index.htmlとして生成するように変更する
=> trailingSlashの設定

.github/workflows/deploy-gcs-frontend.yaml, backend/cmd/dev/main.go, backend/cmd/dev/migrate.go, backend/db_model/account.xo.go, backend/db_model/accountstableselection.xo.go, backend/db_model/cookie.xo.go, backend/db_model/restaurant.xo.go, backend/db_schema/config.json, backend/db_schema/migrations/000001_create-init.up.sql, backend/graph/generated.go, backend/graph/schema.resolvers.go, backend/middleware/issue-cookie.go, graphql/schema.graphqls, webapp/src/app/health/health.tsx, webapp/src/components/provider/ApolloProvider.tsx, webapp/src/gql/__generated__/gql.ts, webapp/src/gql/__generated__/graphql.ts
- **🔧 remove host specification**
- **🗃️ change some serial to uuid**
- **🗃️ set database migration to 1**
- **📦️ update xo generated code**
- **🐛 nil pointer in configMigration**
- **✨ issue-cookie, complete #55**
- **✨ myCUUID to graphql schema**
- **🔧 change graphql uri to adapt local environment**
=> Cookie Middlewareの実装

webapp/src/app/order/allergy/allergy.tsx
https://github.com/user-attachments/assets/359aef0f-e8c8-45ed-8f11-12bfdb7b1412
=> feat: アレルギー情報登録画面を追加

webapp/src/app/order/allergy/allergy.tsx, webapp/src/components/AllergyIcon.tsx
=> update: アレルギーアイコンをコンポーネント化

webapp/src/app/language/page.tsx, webapp/src/app/types/language.ts, webapp/src/features/language/LanguageSelectPage.tsx, webapp/tailwind.config.ts
すみません実装被った()
typesとかはこっちの実装悪くないと思うので取り入れたいの巻
=> feat: 言語選択ページの実装

backend/db_schema/migrations/000002_cart.down.sql, backend/db_schema/seed/000001_init.down.sql, backend/db_schema/seed/000001_init.up.sql, backend/graph/schema.resolvers.go, backend/middleware/issue-cookie.go
- **🗃️ 000002_cart.down.sql**
- **🌱 000001_init.up.sql**
- **🐛 JoinTableSession**
- **🐛 Set-Cookie logic**
=> JoinTableSessionの修正

webapp/src/app/not-found.tsx, webapp/src/gql/__generated__/gql.ts, webapp/src/gql/__generated__/graphql.ts
=> ✨ フロント側のJoinTableSessionの実装

backend/graph/schema.resolvers.go, backend/middleware/issue-cookie.go, backend/service/postgres.go
- **🐛 remove preload**
- **✨ MenuItems resolver**
- **✨ RestaurantID middleware resolver**
=> impl MenuItems

backend/graph/generated.go, backend/graph/schema.resolvers.go, backend/service/postgres.go, graphql/schema.graphqls, webapp/src/gql/__generated__/graphql.ts
=> 🔥 remove unnecessary params in graphqls

webapp/src/features/allergy/AllergenSelectPage.tsx, webapp/src/features/menu/MenuPage.tsx, webapp/src/features/order-cart/OrderCartPage.tsx, webapp/src/gql/__generated__/gql.ts, webapp/src/gql/__generated__/graphql.ts
=> :sparkles: graphql codegen

webapp/src/app/[lang]/allergy/page.tsx, webapp/src/app/[lang]/layout.tsx, webapp/src/app/[lang]/order-mode/page.tsx
=> fix: i18nの非同期処理周りの型エラー修正

backend/graph/generated.go, backend/graph/schema.resolvers.go, backend/middleware/issue-cookie.go, backend/service/postgres.go, graphql/schema.graphqls, webapp/src/gql/__generated__/graphql.ts
- **✨ add lang param**
- **✨ GetAllAllergens,GetMenuCategories**
- **✨ CTX_LANGUAGE**
=> impl gql new

webapp/src/features/menu/MenuPage.tsx
=> style: ショッピングカートボタンを最下部に配置

webapp/src/app/[lang]/dictionaries/ja.json, webapp/src/components/MenuModal.tsx, webapp/src/features/menu/MenuCard.tsx, webapp/src/features/menu/MenuPage.tsx
=> fix: 「カートに追加」のi18n対応忘れ

webapp/src/app/[lang]/dictionaries/de.json, webapp/src/app/[lang]/dictionaries/en.json, webapp/src/app/[lang]/dictionaries/es.json, webapp/src/app/[lang]/dictionaries/fr.json, webapp/src/app/[lang]/dictionaries/it.json, webapp/src/app/[lang]/dictionaries/ja.json, webapp/src/app/[lang]/dictionaries/ko.json, webapp/src/app/[lang]/dictionaries/ru.json, webapp/src/app/[lang]/dictionaries/th.json, webapp/src/app/[lang]/dictionaries/zh.json, webapp/src/app/types/dictionary.ts, webapp/src/components/MenuModal.tsx
=> fix: カートに入れる個数のi18n対応漏れ

infra/envs/dev/google_compute_url_map.tf, infra/envs/dev/google_storage_bucket.tf, infra/envs/dev/imports.tf
=> 🧱 import google_compute_url_map.tf google_storage_bucket.tf

infra/envs/dev/google_compute_backend_bucket.tf, infra/envs/dev/google_compute_backend_service.tf, infra/envs/dev/google_compute_region_neg.tf, infra/envs/dev/google_compute_url_map.tf, infra/envs/dev/google_storage_bucket.tf, infra/envs/dev/imports.tf
import google_storage_bucket, google_compute_backend_service, google_compute_region_network_endpoint_group
=> 🧱 import google_storage_bucket, google_compute_backend_service, google_compute_region_network_endpoint_group

infra/envs/dev/google_compute_backend_service.tf, infra/envs/dev/google_compute_target_https_proxy.tf, infra/envs/dev/google_compute_url_map.tf, infra/envs/dev/imports.tf
- **♻️ refactor tf code**
- **🔥 unlink ssl_certificates from lb_frontend_target_proxy**
=> unlink ssl_certificates from lb_frontend_target_proxy

infra/envs/dev/google_compute_global_forwarding_rule.tf, infra/envs/dev/google_compute_network.tf, infra/envs/dev/google_compute_security_policy.tf, infra/envs/dev/imports.tf
=> 🧱 import google_compute_security_policy

infra/envs/dev/google_cloud_run_v2.tf, infra/envs/dev/imports.tf
frontendでcloud-runを使わなくなったのでdestroyする
=> 🧱 remove frontend service
